services:
  postgres:
    image: postgres:13
    container_name: etl-data-pipeline-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: etl_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql/init/:/docker-entrypoint-initdb.d/  # Только init скрипты
    networks:
      - etl-data-pipeline-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d etl_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      context: .
    container_name: etl-data-pipeline-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=etl_db
    networks:
      - etl-data-pipeline-network
    volumes:
      - ./sql:/app/sql  # Монтируем все SQL файлы

volumes:
  pg_data:

networks:
  etl-data-pipeline-network:
    driver: bridge