version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: etl-data-pipeline-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: etl_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql/init/:/docker-entrypoint-initdb.d/
      - ./sql/dds/:/docker-entrypoint-initdb.d/dds/
    networks:
      - etl-data-pipeline-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d etl_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.0
    container_name: etl-data-pipeline-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dwh_db
    ports:
      - "3307:3306"  # Изменили на 3307 внешний порт
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/dm/:/docker-entrypoint-initdb.d/
    networks:
      - etl-data-pipeline-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    container_name: etl-data-pipeline-app
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=etl_db
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=dwh_db
      - MYSQL_PORT=3306  # Внутренний порт остался 3306
    networks:
      - etl-data-pipeline-network
    volumes:
      - .:/app

volumes:
  pg_data:
  mysql_data:

networks:
  etl-data-pipeline-network:
    driver: bridge